Add exit codes

diff --git a/university-cli b/university-cli
--- a/university-cli
+++ b/university-cli
@@ -1,44 +1,82 @@
 #!/bin/bash
 # Author: Mario Forzanini https://marioforzanini.com
 # Date: 25/05/2021
-# Description: Download video lessons from ariel.unimi.it
-# Dependencies: youtube-dl https://www.youtube-dl.org , wget
+# Description: Download and watch video lessons from ariel.unimi.it
+# Dependencies: mpv https://mpv.io, wget, youtube-dl https://www.youtube-dl.org
 
-OUTPUT_FILE=webpage.html # File name for site's html code
-VIDEOS=( $(grep mp4 $OUTPUT_FILE | cut -d\" -f2) )
-NAMES=( $(grep mp4 $OUTPUT_FILE | cut -d\" -f2 | cut -d: -f3 | sed 's/.mp4.*//') )
+# Exit codes
+EXIT_SUCCESS=0
+EXIT_NO_DEPS=1
+EXIT_NO_INPUT=2
+EXIT_WRONG_ARG=3
+
+function no_dep() {
+	printf "university-cli: $1 not found, install $1 to proceed"
+	exit $EXIT_NO_DEPS
+}
 
 function download() {
-    lesson=$(echo ${NAMES[@]} | dmenu -p "Download Lesson: " -i -c -l 10)
-    youtube-dl --no-check-certificate $(grep "$lesson" $OUTPUT_FILE) -o \
-    "$lesson.mp4"
+	which youtube-dl>/dev/null || no_dep youtube-dl
+	lesson=$(echo ${NAMES[@]} | sed 's/ /\n/g' | dmenu -p "Download Lesson: " -i -l 10)
+	youtube-dl --no-check-certificate $(grep "$lesson" $INPUT_FILE) -o \
+		"$lesson.mp4"
+	exit $EXIT_SUCCESS
 }
 
 function download_all() {
-    for i in ${!VIDEOS[@]}; do
-        youtube-dl --no-check-certificate "${VIDEOS[$i]}" -o "${NAMES[$i]}".mp4
-    done
+	which youtube-dl>/dev/null || no_dep youtube-dl
+	for i in ${!VIDEOS[@]}; do
+		youtube-dl --no-check-certificate "${VIDEOS[$i]}" -o \
+		"${NAMES[$i]}".mp4
+	done
+	exit $EXIT_SUCCESS
+}
+
+function no_input() {
+	printf "university-cli: No input file found: download the html page\
+		in a file called $INPUT_FILE and retry"
+	exit $EXIT_NO_INPUT
 }
 
 function view() {
-    lesson=$(echo ${NAMES[@]} | dmenu -p "Lesson: " -i -c -l 10)
-    if test -z "$lesson.mp4"; then
-        mpv $(grep $lesson $OUTPUT_FILE)
-    else
-        mpv $PWD/$lesson.mp4
-    fi
+	which mpv>/dev/null || no_dep mpv
+	lesson=$(echo ${NAMES[@]} | sed 's/ /\n/g' | dmenu -p "Lesson: " -i -l 10)
+	if test -z "$lesson.mp4"; then
+		mpv $(grep $lesson $INPUT_FILE)
+	else
+		mpv $PWD/$lesson.mp4
+	fi
+	exit $EXIT_SUCCESS
 }
 
-# Read command line options
+# File name for site's html code
+INPUT_FILE=webpage.html
 
-while getopts "hdv" o; do case "${o}" in
-    h) printf "Usage:\n\n\tunimi-cli [OPTIONS]\n\nAvailable options:\n\t-h:\tDisplay this help message\n\t-d:\tDownload all videos\n\t-v:\tChoose a lesson to watch\n\n"
-    ;;
-d) download
-    ;;
-v) view
-    ;;
-*) printf "Invalid option: -%s\\nTry -h for help\n" "$OPTARG" && exit 1
-    ;;
+# Check for the existence of the input file
+test -e $INPUT_FILE || no_input
+
+# Variables
+VIDEOS=($(grep mp4 $INPUT_FILE | cut -d\" -f2))
+NAMES=($(grep mp4 $INPUT_FILE | cut -d\" -f2 | cut -d: -f3 | sed 's/.mp4.*//'))
+
+# Read command line options
+while getopts ":hDdv" o; do case "${o}" in
+	h) printf "Usage:\n\n\tuniversity-cli [OPTIONS] \
+		\n\nAvailable options: \
+		\n\t-h:\tDisplay this help message \
+		\n\t-d:\tChoose a lesson to download \
+		\n\t-D:\tDownload all videos \
+		\n\t-v:\tChoose a lesson to watch\n\n"
+		;;
+	d) download
+		;;
+	D) download_all
+		;;
+	v) view
+		;;
+	*) printf "Invalid option: -%s\\nTry -h for help\n" "$OPTARG" && \
+		exit $EXIT_WRONG_ARG
+		;;
 esac
 done
+
